### ISSUE TITLE
Angular 13: Update library and publish to npm

### ISSUE THREAD

**Issue by MaaxGr** [MaaxGr/ang-jsoneditor#1]
Launch Version 3.0 with Angular 13 support

**Comment by shyandsy** [comment]
there is an error when I try to use your demo

```
core.mjs:6494 ERROR TypeError: (jsoneditor__WEBPACK_IMPORTED_MODULE_0___namespace_cache || (intermediate value)(intermediate value)) is not a constructor
    at JsonEditorComponent.ngOnInit (hardikpatel043-ang-jsoneditor.mjs:69:23)
    at callHook (core.mjs:2551:1)
    at callHooks (core.mjs:2520:1)
    at executeInitAndCheckHooks (core.mjs:2471:1)
    at selectIndexInternal (core.mjs:8416:1)
    at Module.ɵɵadvance (core.mjs:8399:1)
    at JsonComponent_Template (json.component.html:8:14)
    at executeTemplate (core.mjs:9632:1)
    at refreshView (core.mjs:9495:1)
    at refreshComponent (core.mjs:10692:1)
```

json.component.ts
```
import { Component, OnInit } from '@angular/core';
import { JsonEditorOptions } from "@hardikpatel043/ang-jsoneditor";

@Component({
  selector: 'app-json',
  templateUrl: './json.component.html',
  styleUrls: ['./json.component.css']
})

export class JsonComponent implements OnInit {
  public editorOptions: JsonEditorOptions;
  public initialData: any;
  public visibleData: any;

  constructor() {
    this.editorOptions = new JsonEditorOptions()
    this.editorOptions.modes = ['code', 'text', 'tree', 'view'];
    this.initialData = { "products": [{ "name": "car", "product": [{ "name": "honda", "model": [{ "id": "civic", "name": "civic" }, { "id": "accord", "name": "accord" }, { "id": "crv", "name": "crv" }, { "id": "pilot", "name": "pilot" }, { "id": "odyssey", "name": "odyssey" }] }] }] }
    this.visibleData = this.initialData;
  }

  ngOnInit(): void {
  }

  showJson(d: Event) {
    this.visibleData = d;
  }
}
```

json.component.html
```
<div fxLayout="row" fxFlexFill fxLayoutAlign="start center" fxLayoutGap="20px">
    <div fxFlex="50">
        <textarea matInput placeholder="json111" fxFlexFill></textarea>
    </div>
    <div fxFlex="50" style="height:600px;">
        <json-editor fxFlexFill [options]="editorOptions" [data]="initialData" (change)="showJson($event)">
        </json-editor>
        <div>{{ visibleData | json }}</div>
    </div>
</div>
```

**Comment by MaaxGr** [comment]
Hey. Could you try again? I also released a new version with support for Angular 13.
https://github.com/MaaxGr/ang-jsoneditor/releases/tag/13.0.3

Feel free to reopen, if you have any problems.
